spring:
  application:
    name: test-wt
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123


  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
      timeout: 3s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: 2s    