spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: trion

server:
  port: 9087

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

