spring:
  application:
    name: trion

  datasource:
    url: jdbc:trino://172.16.32.4:8080
    username: admin
    password: ""
    driver-class-name: io.trino.jdbc.TrinoDriver

server:
  port: 9081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

